name: 3d_ant_analysis
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - trimesh[easy] # on MacOS may need to run pip install pyembree if embreex is still not avaiable
  - scipy
  - pyglet=1.5.26
  - pip
  - pip:
      - pyembree

#variables:
#  VAR1: valueA
#  VAR2: valueB